FROM python:3.12.7-bullseye

WORKDIR /app

COPY ./src/requirements.txt /app

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY . /app

CMD [ "uvicorn","app:app","--reload","--host","0.0.0.0","--port","80" ]