services:
  app:
    build: .
    image: itau-challenge
    container_name: api
    volumes:
      - .:/app
    ports:
      - 80:80
    command: uvicorn src.app:app --host 0.0.0.0 --port 80 
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: itau_challenge
      OPENAI_API_KEY: INSIRA AQUI A OPENAI_API_KEY
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres-db
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: itau_challenge

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@docker.com
      PGADMIN_DEFAULT_PASSWORD: dev
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: itau_challenge
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin